//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventsEntities : DbContext
    {
        public EventsEntities()
            : base("name=EventsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<federal_districts> federal_districts { get; set; }
        public virtual DbSet<message_categories> message_categories { get; set; }
        public virtual DbSet<message_processing> message_processing { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<popular_group> popular_group { get; set; }
        public virtual DbSet<popular_messages> popular_messages { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<staff_event> staff_event { get; set; }
        public virtual DbSet<status_message> status_message { get; set; }
        public virtual DbSet<type_message> type_message { get; set; }
        public virtual DbSet<type_staff> type_staff { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
