//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events
{
    using System;
    using System.Collections.Generic;
    
    public partial class message_processing
    {
        public int Id_message_processing { get; set; }
        public int Id_message_processing_staff { get; set; }
        public int Id_message_processing_message { get; set; }
        public int Id_message_processing_status_message { get; set; }
        public string answer_comment { get; set; }
    
        public virtual messages messages { get; set; }
        public virtual staff staff { get; set; }
        public virtual status_message status_message { get; set; }
    }
}
