//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events
{
    using System;
    using System.Collections.Generic;
    
    public partial class popular_messages
    {
        public int Id_popular_messages { get; set; }
        public int Id_popular_messages_message { get; set; }
        public int Id_popular_messages_popular_group { get; set; }
        public int vote { get; set; }
    
        public virtual messages messages { get; set; }
        public virtual popular_group popular_group { get; set; }
    }
}
