//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_event
    {
        public int Id_staff_event { get; set; }
        public int Id_staff_event_staff { get; set; }
        public int Id_staff_event_event { get; set; }
    
        public virtual events events { get; set; }
        public virtual staff staff { get; set; }
    }
}
